motdtext:
  - ""
  - "&7               &e&lFrediSaal &6&lNetwork"
  - "&7         &7You are connected to &e&lLobby"
  - ""
  - "&7         &c&lYOUTUBE &rFrediSaalAnimations"
  - "&7                &6&lDISCORD &r/discord"
  - "&7                    &e&lSTORE &r/buy"
  - ""
Discord:
  - "&7Discord is: "